//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommandManager
{
    [Serializable]
    public class commandRequest : Message
    {
        public const string k_RosMessageName = "robot_simple_command_manager_msgs/SetCommandString";
        public override string RosMessageName => k_RosMessageName;

        public string command;

        public commandRequest()
        {
            this.command = "";
        }

        public commandRequest(string command)
        {
            this.command = command;
        }

        public static commandRequest Deserialize(MessageDeserializer deserializer) => new commandRequest(deserializer);

        private commandRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "commandRequest: " +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
