//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommandManager
{
    [Serializable]
    public class commandResponse : Message
    {
        public const string k_RosMessageName = "command_manager/command";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public string message;
        public short code;

        public commandResponse()
        {
            this.success = false;
            this.message = "";
            this.code = 0;
        }

        public commandResponse(bool success, string message, short code)
        {
            this.success = success;
            this.message = message;
            this.code = code;
        }

        public static commandResponse Deserialize(MessageDeserializer deserializer) => new commandResponse(deserializer);

        private commandResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
            deserializer.Read(out this.code);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
            serializer.Write(this.code);
        }

        public override string ToString()
        {
            return "commandResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString() +
            "\ncode: " + code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
