//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageTypes.Actionlib;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Assets
{
    [Serializable]
    public class GoalStatusMsg : Message
    {
        public const string k_RosMessageName = "Assets/GoalStatus";
        public override string RosMessageName => k_RosMessageName;

        public const byte PENDING = 0;
        public const byte ACTIVE = 1;
        public const byte PREEMPTED = 2;
        public const byte SUCCEEDED = 3;
        public const byte ABORTED = 4;
        public const byte REJECTED = 5;
        public const byte PREEMPTING = 6;
        public const byte RECALLING = 7;
        public const byte RECALLED = 8;
        public const byte LOST = 9;
        public GoalIDMsg goal_id;
        public byte status;
        public string text;

        public GoalStatusMsg()
        {
            this.goal_id = new GoalIDMsg();
            this.status = 0;
            this.text = "";
        }

        public GoalStatusMsg(GoalIDMsg goal_id, byte status, string text)
        {
            this.goal_id = goal_id;
            this.status = status;
            this.text = text;
        }

        public static GoalStatusMsg Deserialize(MessageDeserializer deserializer) => new GoalStatusMsg(deserializer);

        private GoalStatusMsg(MessageDeserializer deserializer)
        {
            this.goal_id = GoalIDMsg.Deserialize(deserializer);
            deserializer.Read(out this.status);
            deserializer.Read(out this.text);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal_id);
            serializer.Write(this.status);
            serializer.Write(this.text);
        }

        public override string ToString()
        {
            return "GoalStatusMsg: " +
            "\ngoal_id: " + goal_id.ToString() +
            "\nstatus: " + status.ToString() +
            "\ntext: " + text.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
