//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Assets
{
    [Serializable]
    public class RobotSimpleCommandActionResultMsg : Message
    {
        public const string k_RosMessageName = "robot_simple_command_manager_msgs/CommandStringResult";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public GoalStatusMsg status;
        public RobotSimpleCommandActionResultMsg result;

        public RobotSimpleCommandActionResultMsg()
        {
            this.header = new Std.HeaderMsg();
            this.status = new GoalStatusMsg();
            this.result = new RobotSimpleCommandActionResultMsg();
        }

        public RobotSimpleCommandActionResultMsg(Std.HeaderMsg header, GoalStatusMsg status, RobotSimpleCommandActionResultMsg result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }

        public static RobotSimpleCommandActionResultMsg Deserialize(MessageDeserializer deserializer) => new RobotSimpleCommandActionResultMsg(deserializer);

        private RobotSimpleCommandActionResultMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.status = GoalStatusMsg.Deserialize(deserializer);
            this.result = RobotSimpleCommandActionResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.status);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "RobotSimpleCommandActionResultMsg: " +
            "\nheader: " + header.ToString() +
            "\nstatus: " + status.ToString() +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
