//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RemoteControl
{
    [Serializable]
    public class MoveRequestResponse : Message
    {
        public const string k_RosMessageName = "remote_control/MoveRequest";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public MoveRequestResponse()
        {
            this.success = false;
        }

        public MoveRequestResponse(bool success)
        {
            this.success = success;
        }

        public static MoveRequestResponse Deserialize(MessageDeserializer deserializer) => new MoveRequestResponse(deserializer);

        private MoveRequestResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "MoveRequestResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
